# Generated by Django 4.2.7 on 2025-07-29 00:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('esg_assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('comment', 'View & Comment'), ('edit', 'View, Comment & Edit'), ('admin', 'Full Access')], default='view', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('contributions_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Collaboration Participant',
                'verbose_name_plural': 'Collaboration Participants',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, choices=[('sustainability', 'Sustainability'), ('operations', 'Operations'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('legal', 'Legal & Compliance'), ('it', 'Information Technology'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('expertise_areas', models.JSONField(default=list, help_text='Areas of ESG expertise')),
                ('certifications', models.JSONField(default=list, help_text='Professional certifications')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('task_notifications', models.BooleanField(default=True)),
                ('report_notifications', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('total_reports_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeamCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collaboration_type', models.CharField(choices=[('shared_assessment', 'Shared Assessment'), ('shared_task', 'Shared Task'), ('shared_report', 'Shared Report'), ('team_project', 'Team Project')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='companies.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_collaborations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='collaborations', through='user_management.CollaborationParticipant', to=settings.AUTH_USER_MODEL)),
                ('related_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esg_assessment.esgassessment')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.generatedreport')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Team Collaboration',
                'verbose_name_plural': 'Team Collaborations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_registration', models.BooleanField(default=False)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('default_user_role', models.CharField(default='contributor', max_length=20)),
                ('password_expiry_days', models.IntegerField(default=0)),
                ('require_2fa', models.BooleanField(default=False)),
                ('session_timeout_hours', models.IntegerField(default=24)),
                ('allow_external_sharing', models.BooleanField(default=False)),
                ('max_team_size', models.IntegerField(default=50)),
                ('admin_notification_email', models.EmailField(blank=True, max_length=254)),
                ('notify_on_new_user', models.BooleanField(default=True)),
                ('notify_on_role_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_management_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company User Settings',
                'verbose_name_plural': 'Company User Settings',
            },
        ),
        migrations.AddField(
            model_name='collaborationparticipant',
            name='collaboration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teamcollaboration'),
        ),
        migrations.AddField(
            model_name='collaborationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_manage_user_id_dad219_idx'), models.Index(fields=['session_key'], name='user_manage_session_341d53_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('assessment_started', 'Assessment Started'), ('assessment_completed', 'Assessment Completed'), ('report_generated', 'Report Generated'), ('data_exported', 'Data Exported'), ('settings_updated', 'Settings Updated'), ('team_invited', 'Team Member Invited'), ('role_changed', 'Role Changed')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'created_at'], name='user_manage_user_id_eebff5_idx'), models.Index(fields=['company', 'created_at'], name='user_manage_company_f0476d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, help_text='Role-specific permissions configuration')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Role',
                'verbose_name_plural': 'Team Roles',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'ESG Manager'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional invitation message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='companies.company')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='user_manage_email_5f82f2_idx'), models.Index(fields=['token'], name='user_manage_token_424a8b_idx'), models.Index(fields=['expires_at'], name='user_manage_expires_eed929_idx')],
                'unique_together': {('company', 'email', 'status')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='collaborationparticipant',
            unique_together={('collaboration', 'user')},
        ),
    ]
