# Generated by Django 4.2.7 on 2025-08-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, help_text='External ID from frontend task generator for sync purposes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='framework_tags',
            field=models.JSONField(default=list, help_text='Framework tags from frontend task generation'),
        ),
        migrations.AddField(
            model_name='task',
            name='sector',
            field=models.CharField(blank=True, help_text='Business sector this task was generated for', max_length=100),
        ),
    ]
