# Generated by Django 4.2.7 on 2025-08-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the company and its activities', null=True, verbose_name='Company Description'),
        ),
    ]
